### ISSUE TITLE
Operator Redesign

### ISSUE THREAD

**Issue by astefanutti** [project-codeflare/codeflare-operator#279]
Epic issue that breaks down tasks, to implement the operator redesign, as described in project-codeflare/adr#9.

- [x] Configuration:
  - [x] project-codeflare/instascale#132
  - [x] project-codeflare/multi-cluster-app-dispatcher#622
  - [x] #273
        (depends on the two issues above, on top of #216)
- [ ] Operator (on top of #216):
  - [x] #281 
  - [x] #278
  - [x] #280
- [x] Automation:
  - [x] project-codeflare/instascale#133
  - [x] project-codeflare/multi-cluster-app-dispatcher#629
- [x] OpenDataHub:
  - [x] opendatahub-io/distributed-workloads#113
  - [x] opendatahub-io/distributed-workloads#112
  - [x] opendatahub-io/distributed-workloads#114
